@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as User
participant ":UIReview_C" as rev1

activate User

User -> rev1: POST/reviews
rev1 --> User: Review
User -> rev1: PUT/{reviewId}/approve/{reviewStatus}
rev1 --> User: String
User -> rev1: DELETE/{reviewId}/remove
rev1 --> User: String
@enduml