@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

participant ":UIReview_Q" as rev
participant ":Review_Q" as rev1

rev -> rev1: GET/reviews/status/{reviewId}
rev1 --> rev: String
@enduml